### ISSUE TITLE
Cannot run wis2box-api following the readme

### ISSUE THREAD

**Issue by faysal-ishtiaq** [wmo-im/wis2box-api#22]
I am trying to install and run `wis2box-api` by following these instructions <https://github.com/wmo-im/wis2box-api#installing-the-package>

When I try running
```
export FLASK_APP=wis2box_api.app
flask run
```
it returns this error
```RuntimeError: PYGEOAPI_CONFIG environment variable not set```
when I set that as
```export PYGEOAPI_CONFIG=docker/pygeoapi-config.yml```
it returns
```OSError: Undefined environment variable WIS2BOX_API_URL in config```
When I set
```export WIS2BOX_API_URL=<http://localhost:5000>```
it returns
```OSError: Undefined environment variable WIS2BOX_BASEMAP_URL in config```
when I set that to
```export WIS2BOX_BASEMAP_URL=<http://test.dev>```
it returns
```OSError: Undefined environment variable WIS2BOX_BASEMAP_ATTRIBUTION in config```
when I set that as
```export WIS2BOX_BASEMAP_ATTRIBUTION=test```
it returns
```OSError: Undefined environment variable WIS2BOX_DATADIR in config```
when I set that as
```export WIS2BOX_DATADIR=data```
it runs.
But when I go to <http://localhost:5000> it redirects to <https://docs.wis2box.wis.wmo.int/en/latest/>
So, I tried <http://localhost:5000/oapi/admin> and it returns `internal server error` with

```

[2023-01-16T19:16:08Z] {/home/faysal/sandbox/wis2api/my-env/lib/python3.10/site-packages/Flask-2.2.2-py3.10.egg/flask/app.py:1741} ERROR - Exception on /oapi/admin [GET]
Traceback (most recent call last):
  File "/home/faysal/sandbox/wis2api/my-env/lib/python3.10/site-packages/pygeoapi/util.py", line 355, in render_j2_template
    template = env.get_template(template)
  File "/home/faysal/sandbox/wis2api/my-env/lib/python3.10/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/home/faysal/sandbox/wis2api/my-env/lib/python3.10/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/faysal/sandbox/wis2api/my-env/lib/python3.10/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/faysal/sandbox/wis2api/my-env/lib/python3.10/site-packages/jinja2/loaders.py", line 214, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: admin/index.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/faysal/sandbox/wis2api/my-env/lib/python3.10/site-packages/Flask-2.2.2-py3.10.egg/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/faysal/sandbox/wis2api/my-env/lib/python3.10/site-packages/Flask-2.2.2-py3.10.egg/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/faysal/sandbox/wis2api/my-env/lib/python3.10/site-packages/Flask_Cors-3.0.10-py3.10.egg/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/faysal/sandbox/wis2api/my-env/lib/python3.10/site-packages/Flask-2.2.2-py3.10.egg/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/faysal/sandbox/wis2api/my-env/lib/python3.10/site-packages/Flask-2.2.2-py3.10.egg/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/faysal/sandbox/wis2api/wis2box-api/wis2box_api/flask_admin.py", line 58, in admin
    return get_response(admin_.admin(request))
  File "/home/faysal/sandbox/wis2api/my-env/lib/python3.10/site-packages/pygeoapi/api.py", line 169, in inner
    return func(cls, req_out)
  File "/home/faysal/sandbox/wis2api/wis2box-api/wis2box_api/admin.py", line 160, in admin
    content = render_j2_template(
  File "/home/faysal/sandbox/wis2api/my-env/lib/python3.10/site-packages/pygeoapi/util.py", line 363, in render_j2_template
    template = env.get_template(template)
  File "/home/faysal/sandbox/wis2api/my-env/lib/python3.10/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/home/faysal/sandbox/wis2api/my-env/lib/python3.10/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/faysal/sandbox/wis2api/my-env/lib/python3.10/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/faysal/sandbox/wis2api/my-env/lib/python3.10/site-packages/jinja2/loaders.py", line 214, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: admin/index.html
[2023-01-16T19:16:08Z] {/home/faysal/sandbox/wis2api/my-env/lib/python3.10/site-packages/Werkzeug-2.2.2-py3.10.egg/werkzeug/_internal.py:224} INFO - 127.0.0.1 - - [16/Jan/2023 19:16:08] "GET /oapi/admin HTTP/1.1" 500 -

```

could you please suggest how to fix this error?

Also I think it would help people getting started with it a lot if the readme discussed the required configurations.

**Comment by maaikelimper** [comment]
wis2box-api is a service for wis2box, please refer to wis2box-documentation here https://docs.wis2box.wis.wmo.int
