### ISSUE TITLE
wis2box-api 1.0b5 flask error

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box-api#36]
The 1.0b5 version will randomly crash with this output:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/ctx.py", line 401, in pop
    self.app.do_teardown_request(exc)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2035, in do_teardown_request
    for name in chain(request.blueprints, (None,)):
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request. Consult the documentation on testing for
information about how to avoid this problem.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base_async.py", line 55, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/lib/python3/dist-packages/gunicorn/workers/ggevent.py", line 143, in handle_request
    super().handle_request(listener_name, req, sock, addr)
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base_async.py", line 106, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2206, in wsgi_app
    ctx.pop(error)
  File "/usr/local/lib/python3.8/dist-packages/flask/ctx.py", line 407, in pop
    ctx = _cv_request.get()
LookupError: <ContextVar name='flask.request_ctx' at 0x7f0fb8d9fd10>

I suspect it has something to do with the different way the wis2box-api is dockerized (see changes in Dockerfile)

**Comment by maaikelimper** [comment]
this was fixed
